AminoAcids={Ala:{shortName:"A",codes:["GCU","GCC","GCA","GCG"],type:"Nonpolar",longName:"Alanine"},Leu:{shortName:"L",codes:"UUA UUG CUU CUC CUA CUG".split(" "),type:"Nonpolar",longName:"Leucine"},Arg:{shortName:"R",codes:"CGU CGC CGA CGG AGA AGG".split(" "),type:"Polar",longName:"Arginine"},Lys:{shortName:"K",codes:["AAA","AAG"],type:"Basic",longName:"Lysine"},Asn:{shortName:"N",codes:["AAU","AAC"],type:"Polar",longName:"Asparagine"},Met:{shortName:"M",codes:["AUG"],type:"Nonpolar",longName:"Methionine"},
Asp:{shortName:"D",codes:["GAU","GAC"],type:"Nonpolar",longName:"Aspartic acid"},Phe:{shortName:"F",codes:["UUU","UUC"],type:"Nonpolar",longName:"Phenylalanine"},Cys:{shortName:"C",codes:["UGU","UGC"],type:"Polar",longName:"Cysteine"},Pro:{shortName:"P",codes:["CCU","CCC","CCA","CCG"],type:"Nonpolar",longName:"Proline"},Gln:{shortName:"Q",codes:["CAA","CAG"],type:"Polar",longName:"Glutamine"},Ser:{shortName:"S",codes:"UCU UCC UCA UCG AGU AGC".split(" "),type:"Polar",longName:"Serine"},Glu:{shortName:"E",
codes:["GAA","GAG"],type:"Nonpolar",longName:"Glutamic acid"},Thr:{shortName:"T",codes:["ACU","ACC","ACA","ACG"],type:"Polar",longName:"Threonine"},Gly:{shortName:"G",codes:["GGU","GGC","GGA","GGG"],type:"Polar",longName:"Glycine"},Trp:{shortName:"W",codes:["UGG"],type:"Nonpolar",longName:"Tryptophan"},His:{shortName:"H",codes:["CAU","CAC"],type:"Basic",longName:"Histidine"},Tyr:{shortName:"Y",codes:["UAU","UAC"],type:"Polar",longName:"Tyrosine"},Ile:{shortName:"I",codes:["AUU","AUC","AUA"],type:"Nonpolar",
longName:"Isoleucine"},Val:{shortName:"V",codes:["GUU","GUC","GUA","GUG"],type:"Nonpolar",longName:"Valine"},START:{shortName:"START",codes:["AUG"],type:"START",longName:"Methionine"},STOP:{shortName:"STOP",codes:["UAG","UGA","UAA"],type:"STOP",longName:"Stop codon"}};$(function(){function A(){$("#decodedlabel").hide();$("#decoded").hide();$("#allORFs").html("");var p=$("#sequence").attr("value"),p=G(p);K=p.length;var a=p;$("#length").html(a.length);for(var a=p,b=0,c=0;c<a.length;c++){var n=a.charAt(c);("g"==n||"G"==n||"c"==n||"C"==n)&&b++}c=0;0!=a.length&&(c=b/a.length);$("#perc").html(Math.round(100*c));$("#minlen").html(x);a=p;b=$("#scrollbar");b.find(".ui-slider-handle");c=$("#canvas").width();n=c/((1+a.length)*f);1<n&&(n=1);Math.round(n*b.width());b.slider("option",
"min",0);b.slider("option","max",Math.round(a.length-c/f));b.slider("option","value",a.length/4);d=a.length/4;v=C(p);H=C(D(p));E(p)}function G(a){return a.replace(/[^atgcu]/mig,"").replace(/t/mig,"u").toUpperCase()}function J(a){"G"==a?a="C":"g"==a?a="c":"C"==a?a="G":"c"==a?a="g":"a"==a?a="u":"A"==a?a="U":"T"==a?a="A":"t"==a?a="a":"u"==a?a="a":"U"==a&&(a="A");return a}function D(a){for(var b="",c=0;c<a.length;c++){var k=a.charAt(c);"G"==k?k="C":"g"==k?k="c":"C"==k?k="G":"c"==k?k="g":"a"==k?k="u":
"A"==k?k="U":"T"==k?k="A":"t"==k?k="a":"u"==k?k="a":"U"==k&&(k="A");b=k+b}return b}function l(){d=$("#scrollbar").slider("option","value");var a=$("#sequence").attr("value"),a=G(a);E(a)}function w(a,b,c,k){k.clearRect(0,0,b,c);k.fillStyle="#f0f0f0";k.fillRect(0,0,b,100)}function B(a,b,c,k,n){if(!(null==v||null==H)){b=n.fillStyle;n.fillStyle="#e0e0e0";n.fillRect(0,10,c,6);n.fillRect(0,18,c,6);n.fillRect(0,26,c,6);n.fillRect(0,35,c,12);n.fillRect(0,50,c,6);n.fillRect(0,58,c,6);n.fillRect(0,66,c,6);
k=a.length/c;for(var e=0,g=0,h=0,f=0;f<a.length;f++){var d=a.charAt(f);("g"==d||"G"==d||"c"==d||"C"==d)&&e++;g++;g>k&&(e=Math.round(256-256*e/g),n.fillStyle="rgb("+e+","+e+","+e+")",n.fillRect(h,35,1,12),e=g=0,h++)}for(f=0;3>f;f++)for(var e=v[f],d=g=0,l=f;l<a.length;l+=3)d+=3,h=e[l],"object"==typeof h&&g++,d>k&&(0<g&&(h=Math.round(l/a.length*c),n.fillStyle=g==d/3?"rgb(64,128,64)":"rgb(64,200,64)",n.fillRect(h,8*f+11,1,5)),d=g=0);for(f=0;3>f;f++){e=H[f];d=g=0;for(l=f;l<a.length;l+=3)d+=3,h=e[l],"object"==
typeof h&&g++,d>k&&(0<g&&g==d/3&&(h=Math.round(l/a.length*c),n.fillRect(c-h,8*(5+f)+11,1,5)),g=!1,d=0)}n.fillStyle=b}}function E(a){function c(a,b,p,k){"STOP"==a&&(a=(p-d)*f,b=135+15*b,g.beginPath(),g.moveTo(a,b),g.lineTo(a+3*f,b),g.lineTo(a+3*f+3*k,b+7),g.lineTo(a+3*f,b+y),g.lineTo(a,b+15),g.lineTo(a+3*k,b+7),g.fill(),g.closePath())}function u(a,b,c,p){"Met"==a&&(a=(c-d)*f,b=135+15*b,g.beginPath(),g.moveTo(a,b),g.lineTo(a+3*f,b),g.lineTo(a+3*f+3*p,b+7),g.lineTo(a+3*f,b+y),g.lineTo(a,b+15),g.lineTo(a+
3*p,b+7),g.fill(),g.closePath())}var k=document.getElementById("canvas"),n=k.width,t=k.height;n!=k.clientWidth&&(k.width=k.clientWidth,n=k.width,h=null);var g=k.getContext("2d");w(k,n,t,g);a!=b||e!=x||null==h?(B(a,k,n,t,g),h=g.getImageData(0,0,n,t),b=a,e=x):g.putImageData(h,0,0);t=10*Math.round(d/10);k=10*Math.round((d+n/f)/10);g.fillStyle="rgba(0,0,0,.5)";g.fillRect(t/a.length*n,5,(t-k)/a.length*n,70);g.fillStyle="#000000";g.beginPath();g.moveTo(0,100);g.lineTo(t/a.length*n,75);g.moveTo(k/a.length*
n,75);g.lineTo(n,100);g.stroke();g.closePath();g.font="bold 12px verdana";for(var m=t;m<=k;m+=10){var l=g.measureText(m).width;g.fillText(m,(m-d)*f-(l-f)/2,110);g.fillText(m,(m-d)*f-(l-f)/2,270);g.fillRect((m-d)*f,113,f,5);g.fillRect((m-d)*f,254,f,5)}g.font="normal 12px verdana";l=g.measureText("A").width;for(m=d;m<=Math.round(d+n/f);m++){var s=a.charAt(m);g.fillText(s,(m-d)*f-(l-f)/2,130);s=J(s);g.fillText(s,(m-d)*f-(l-f)/2,252)}g.lineWidth=0.25;g.beginPath();for(s=0;7>=s;s++)g.moveTo(0,135+15*s),
g.lineTo(n,135+15*s);for(m=t-3;m<=k;m+=1)s=m%3,g.moveTo((m-d)*f,135+s*y),g.lineTo((m-d)*f+3,142+s*y),g.lineTo((m-d)*f,150+s*y),g.moveTo((m-d)*f,195+s*y),g.lineTo((m-d)*f-3,202+s*y),g.lineTo((m-d)*f,210+s*y);g.stroke();g.closePath();oldFillStyle=g.fillStyle;g.fillStyle="#008000";for(m=3<t?t-3:0;m<=k;m+=1)s=m%3,"object"==typeof v[s][m]&&(l=(m-d)*f,n=15*s+139,g.fillRect(l,n,3*f,f/2)),"object"==typeof H[s][a.length-m]&&(l=(m-d)*f,n=15*(s+4)+139,g.fillRect(l,n,3*f,f/2));g.fillStyle="#ff0000";for(m=3<t?
t-3:0;m<=k;m+=1){var s=m%3,l=a.substring(m,m+3),n=CodonMap[l],r=CodonMap[D(l)];c(n,s,m,1);c(r,s+4,m,-1)}g.fillStyle=oldFillStyle;g.fillStyle="rgb(96,96,192)";for(m=3<t?t-3:0;m<=k;m+=1)s=m%3,l=a.substring(m,m+3),n=CodonMap[l],r=CodonMap[D(l)],u(n,s,m,1),u(r,s+4,m,-1);g.fillStyle=oldFillStyle;for(m=t-3;m<=k;m+=1)s=m%3,l=a.substring(m,m+3),n=CodonMap[l],r=CodonMap[D(l)],l=g.measureText(n).width,t=g.measureText(r).width,g.fillText(n,(m-d)*f+2-(l-3*f)/2,147+s*y),g.fillText(r,(m-d)*f-2-(t-3*f)/2,207+s*
y)}function L(){CodonMap={};for(aa in AminoAcids)if("START"!=aa){var a=AminoAcids[aa].codes;for(i in a)CodonMap[a[i]]=aa}}function z(a,b,c){if(100>=b){var k=document.getElementById("canvas").width,e=$("#sequence").attr("value"),e=G(e),k=Math.round((e.length-k/f)*a/k);0>k&&(k=0);k>e.length&&(k=e.length);e=$("#scrollbar");e.slider("option","value",k);l()}100<=b&&null!=c?(b=a-c.x,Math.abs(b)>f&&(k=Math.round(b/f),c.x+=k*f,e=$("#scrollbar"),d-=k,e.slider("option","value",d),l())):100<=b&&null==c&&(k=
Math.round(a/f),k=d+k-1,c=Math.ceil((b-135)/y),1<=c&&3>=c?(b=v[c-1][k],F={from:b.from,to:b.to,forward:!0},I(),console.info("decode forward on bpi: "+k+" row:"+c+" "+b.from+"-"+b.to)):5<=c&&7>=c&&(b=H[c-5][K-k],F={from:b.from,to:b.to,forward:!1},I(),console.info("decode reverse on bpi: "+k+" row:"+c+" "+b.from+"-"+b.to)))}function I(){$("#decodedlabel").show();$("#decoded").show();var b=F.from,c=F.to,e=F.forward,k=$("#sequence").attr("value"),k=G(k);e||(k=D(k));e="";for(b+=3;b<c;b+=3)var h=k.substring(b,
b+3),h=CodonMap[h],e=a?e+(h+" "):e+AminoAcids[h].shortName;$("#decoded").html(e);$("#allORFs").html("")}function C(a,b){for(var c={},k=0;3>k;k++){c[k]={};for(var e=0,h=!1,g=k;g<a.length;g+=3){var f=a.substring(g,g+3),f=CodonMap[f];if("STOP"==f){if(g-e>=3*x)for(h={from:e,to:g};e<=g;e++)c[k][e]=h;e=g;h=!0}else!h&&"MET"==f&&(e=g,h=!0)}}return c}function r(a){for(var b=[],c=0;3>c;c++)for(var e=0,h=!1,f=c;f<a.length;f+=3){var g=a.substring(f,f+3),g=CodonMap[g];if("STOP"==g){if(f-e>=3*x){for(var h=f,d=
"",l="",f=e+3;f<h;f+=3)g=a.substring(f,f+3),g=CodonMap[g],d+=AminoAcids[g].shortName,l+=g+" ";b.push({from:e,to:f,l3:l,l1:d})}e=f;h=!0}else!h&&"MET"==g&&(e=f,h=!0)}return b}var x=80,d=0,f=12,y=15,v=null,H=null,K=-1,F=null,a=!0,c=null;(function(){var a=!0;Modernizr.canvas||(a=!1);if(a){var b=navigator.userAgent.toLowerCase(),c;if(c=-1!=b.indexOf("mozilla")&&-1==b.indexOf("spoofer")&&-1==b.indexOf("compatible")&&-1==b.indexOf("opera")&&-1==b.indexOf("webtv")&&-1==b.indexOf("hotjava")){if("Gecko"!=navigator.product)c=
-1;else{c=0;for(var e=navigator.userAgent.toLowerCase(),h=e.indexOf("rv:"),f=e.indexOf(")",h),e=e.substring(h+3,f).split("."),h=1,f=0;f<e.length;f++){var g=parseInt(e[f]);c+=g/h;h*=100}}c=2>c}if(c)a=!1;else{if(b=-1!=b.indexOf("msie")&&-1==b.indexOf("opera"))b=-1,"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(b=parseFloat(RegExp.$1)),b=9>b;b&&(a=!1)}}a||alert("This site does support your browser. Please upgrade to modern browser.")})();
(function(){L();$("#decodedlabel").hide();$("#decoded").hide();$("#sequence").change(function(){A()});$("#sequence").keypress(function(){A()});$("#new_window").button();$("#changelength").button();$("#changelength").click(function(){var a=Math.round(prompt("Minimum ORF length: ",x));0<a&&1E4>a&&($("#wait").html("Recalculating putative ORFs"),$("#wait").dialog("open"),x=a,window.setTimeout(function(){$("#minlen").html(x);A();$("#wait").dialog("close")},10))});$("#decoded31").button();$("#decoded31").click(function(){(a=
!this.checked)?$("#decoded31").button("option","label","3 letter code"):$("#decoded31").button("option","label","1 letter code");null!=F&&I()});$("#decodedblast").button();$("#decodedblast").click(function(){a=!1;$("#decoded31").button("option","label","1 letter code");I();var b="http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&QUERY="+$("#decoded").html();window.open(b,"blast")});$("#reversecomplement").button();$("#reversecomplement").click(function(){$("#wait").html("Calculating reverse complement");
$("#wait").dialog("open");window.setTimeout(function(){var a=G($("#sequence").attr("value")),a=D(a);$("#sequence").attr("value",a);A();$("#wait").dialog("close")},5)});$("#allorfs").button();$("#allorfs").click(function(){$("#wait").html("Calculating all ORFs, this may take a while...");$("#wait").dialog("open");window.setTimeout(function(){$("#decodedlabel").hide();$("#decoded").hide();var b="",c=$("#sequence").attr("value"),c=G(c),e=r(c),c=r(D(c)),b=b+'<div style="background-color:rgb(225,255,225);font-weight:bold;font-size:18px;">Forward decoding</div><div style="width:100%;word-break:break-all">';
for(i in e)var h=e[i],f="http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&QUERY="+h.l1,b=b+("<span style='width:600px'><b>Forward "+h.from+"-"+h.to+"</b></span> <a class='ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only' target='blast' style='height:20px;width:125px' href='"+f+"'><span  style='font-size:12px;width:50px'> Run Blast search </span></a><br>"+(a?h.l3:h.l1)+"<br>");b+='</div><div style="background-color:rgb(225,255,225);font-weight:bold;font-size:18px;">Reverse decoding</div><div style="width:100%;word-break:break-all">';
for(i in c)h=c[i],f="http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&QUERY="+h.l1,b+="<span style='width:600px'><b>Reverse "+h.from+"-"+h.to+"</b></span> <a class='ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only' target='blast' style='height:20px;width:125px' href='"+f+"'><span  style='font-size:12px;width:50px'> Run Blast search </span></a><br>"+(a?h.l3:h.l1)+"<br>";$("#allORFs").html(b);$("#wait").dialog("close")},5)});$("#scrollbar").slider();$("#scrollbar").slider("option",
"slide",l);$("#canvas").click(function(a){var b=document.getElementById("canvas");z(a.pageX-b.offsetLeft,a.pageY-b.offsetTop,null)});$("#canvas").mousedown(function(a){var b=document.getElementById("canvas");c={x:a.pageX-b.offsetLeft,y:a.pageY-b.offsetTop};return!1});$("#canvas").mouseup(function(a){c=null});$("#canvas").mousemove(function(a){if(null!=c){var b=document.getElementById("canvas");z(a.layerX-b.offsetLeft,a.layerY-b.offsetTop,c)}});Modernizr.touch&&$("#canvas").each(function(){this.ontouchstart=
function(a){a=a.touches[0];var b=document.getElementById("canvas");c={x:a.clientX-b.offsetLeft,y:a.clientY-b.offsetTop}};this.ontouchmove=function(a){a=a.touches[0];var b=document.getElementById("canvas");z(a.clientX-b.offsetLeft,a.clientY-b.offsetTop,c)};this.ontouchend=function(a){c=null}});$("#wait").dialog();$("#wait").html("Loading sample sequence");$("#wait").dialog("open");window.setTimeout(function(){$().ready(function(){$.ajax({url:"sequence.txt",success:function(a){$("#sequence").html(a);
A()}});$("#wait").dialog("close")},10)})})();var b=null,e=0,h=null});(function(A,G,J,D,l){function w(a,c){a?c?(C=f({},C,a),r=f({},C)):r=f({},r,a):r=f({},C);return this}function B(a,c){a.fillStyle=c.fillStyle;a.strokeStyle=c.strokeStyle;a.lineWidth=c.strokeWidth;a.lineCap=c.strokeCap;a.lineJoin=c.strokeJoin;c.rounded&&(a.lineCap="round",a.lineJoin="round");a.shadowOffsetX=c.shadowX;a.shadowOffsetY=c.shadowY;a.shadowBlur=c.shadowBlur;a.shadowColor=c.shadowColor;a.globalAlpha=c.opacity;a.globalCompositeOperation=c.compositing}function E(a,c){c.mask&&(a.save(),a.clip());
c.closed?(a.closePath(),a.fill(),a.stroke()):(a.fill(),a.stroke(),a.closePath())}function L(a){return a.inDegrees?v/180:1}function z(a,c,b,e){var h=L(c);a.save();c.fromCenter||(c.x+=b/2,c.y+=e/2);c.angle&&(a.translate(c.x,c.y),a.rotate(c.angle*h),a.translate(-c.x,-c.y));return h}function I(a){x.push(a);return a}var C,r,x,d=A.fn,f=A.extend,y=A.event.fix,v=J.PI,H=J.round,K=J.sin,F=J.cos;C={width:0,height:0,cornerRadius:0,fillStyle:"transparent",strokeStyle:"transparent",strokeWidth:1,strokeCap:"butt",
strokeJoin:"miter",rounded:!1,shadowX:0,shadowY:0,shadowBlur:3,shadowColor:"transparent",opacity:1,compositing:"source-over",mask:!1,x:0,y:0,x1:0,y1:0,x2:0,y2:0,radius:0,start:0,end:360,ccw:!1,inDegrees:!0,fromCenter:!0,closed:!1,sides:3,angle:0,text:"",font:"normal 12pt sans-serif",align:"center",baseline:"middle",source:"",repeat:"repeat"};r=f({},C);d.jCanvas=w;d.loadCanvas=function(a){return this[0].getContext(a||"2d")};d.draw=function(a){var c;for(c=0;c<this.length;c+=1)a.call(this[c],this[c].getContext("2d"));
return this};d.gradient=function(a){var c=this[0].getContext("2d");a=f({},r,a);for(var b,e=0,h=1,c=a.r1!==l||a.r2!==l?c.createRadialGradient(a.x1,a.y1,a.r1,a.x2,a.y2,a.r2):c.createLinearGradient(a.x1,a.y1,a.x2,a.y2);a["c"+h]!==l;)e+=1,h+=1;for(h=1;h<=e;h+=1)b=H(100/(e-1)*(h-1))/100,a["s"+h]===l&&(a["s"+h]=b),c.addColorStop(a["s"+h],a["c"+h]);return c};d.pattern=function(a){function c(){return p.complete?(d=e.createPattern(p,h.repeat),!0):!1}function b(){c();h.load&&h.load.call(this[0],d)}var e=this[0].getContext("2d"),
h=f({},r,a),p=new D,d;p.src=h.source;h.load?p.onload=b:c()||(p.onload=b);return d};d.clearCanvas=function(a){var c,b,e=f({},r,a);for(b=0;b<this.length;b+=1)c=this[b].getContext("2d"),z(c,e,e.width,e.height),a?c.clearRect(e.x-e.width/2,e.y-e.height/2,e.width,e.height):c.clearRect(0,0,this[b].width,this[b].height);return this};d.saveCanvas=function(){for(var a=0;a<this.length;a+=1)this[a].getContext("2d").save();return this};d.restoreCanvas=function(){for(var a=0;a<this.length;a+=1)this[a].getContext("2d").restore();
return this};d.scaleCanvas=function(a){var c,b=f({},r,a);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),a.save(),a.translate(b.x,b.y),a.scale(b.width,b.height),a.translate(-b.x,-b.y);return this};d.translateCanvas=function(a){var c,b=f({},r,a);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),a.save(),a.translate(b.x,b.y);return this};d.rotateCanvas=function(a){var c,b=f({},r,a);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),z(a,b,0,0);return this};d.drawRect=function(a){var c,b=
f({},r,a),e,h,p,d,l;for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),B(a,b),z(a,b,b.width,b.height),b.cornerRadius?(e=b.x-b.width/2,h=b.y-b.height/2,p=b.x+b.width/2,d=b.y+b.height/2,l=b.cornerRadius,0>p-e-2*l&&(l=(p-e)/2),0>d-h-2*l&&(l=(d-h)/2),a.beginPath(),a.moveTo(e+l,h),a.lineTo(p-l,h),a.arc(p-l,h+l,l,3*v/2,2*v),a.lineTo(p,d-l),a.arc(p-l,d-l,l,0,v/2),a.lineTo(e+l,d),a.arc(e+l,d-l,l,v/2,v),a.lineTo(e,h+l),a.arc(e+l,h+l,l,v,3*v/2)):(a.beginPath(),a.rect(b.x-b.width/2,b.y-b.height/2,b.width,
b.height),a.restore()),E(a,b);return this};d.drawArc=function(a){var c,b,e=f({},r,a);!e.inDegrees&&360===e.end&&(e.end=2*v);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),B(a,e),b=z(a,e,e.radius,e.radius),a.beginPath(),a.arc(e.x,e.y,e.radius,e.start*b-v/2,e.end*b-v/2,e.ccw),a.restore(),E(a,e);return this};d.drawEllipse=function(a){var c,b=f({},r,a),e=b.width*(4/3);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),B(a,b),z(a,b,b.width,b.height),a.beginPath(),a.moveTo(b.x,b.y-b.height/2),
a.bezierCurveTo(b.x-e/2,b.y-b.height/2,b.x-e/2,b.y+b.height/2,b.x,b.y+b.height/2),a.bezierCurveTo(b.x+e/2,b.y+b.height/2,b.x+e/2,b.y-b.height/2,b.x,b.y-b.height/2),a.restore(),E(a,b);return this};d.drawLine=function(a){var c,b=f({},r,a),e=2,h,p;for(c=0;c<this.length;c+=1){a=this[c].getContext("2d");B(a,b);a.beginPath();for(a.moveTo(b.x1,b.y1);;){h=b["x"+e];p=b["y"+e];if(h!==l&&p!==l)a.lineTo(h,p);else break;e+=1}E(a,b)}return this};d.drawQuad=function(a){var c,b=f({},r,a),e=2,h,p,d,u;for(c=0;c<this.length;c+=
1){a=this[c].getContext("2d");B(a,b);a.beginPath();for(a.moveTo(b.x1,b.y1);;){h=b["x"+e];p=b["y"+e];d=b["cx"+(e-1)];u=b["cy"+(e-1)];if(h!==l&&p!==l&&d!==l&&u!==l)a.quadraticCurveTo(d,u,h,p);else break;e+=1}E(a,b)}return this};d.drawBezier=function(a){var c,b=f({},r,a),e=2,h=1,d,q,u,k,n,t;for(c=0;c<this.length;c+=1){a=this[c].getContext("2d");B(a,b);a.beginPath();for(a.moveTo(b.x1,b.y1);;){d=b["x"+e];q=b["y"+e];u=b["cx"+h];k=b["cy"+h];n=b["cx"+(h+1)];t=b["cy"+(h+1)];if(d!==l&&q!==l&&u!==l&&k!==l&&
n!==l&&t!==l)a.bezierCurveTo(u,k,n,t,d,q);else break;e+=1;h+=2}E(a,b)}return this};d.drawText=function(a){var c,b=f({},r,a);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),B(a,b),a.textBaseline=b.baseline,a.textAlign=b.align,a.font=b.font,a.strokeText(b.text,b.x,b.y),a.fillText(b.text,b.x,b.y);return this};d.drawImage=function(a){function c(a){return q.complete?(u=q.width/q.height,d.sx===l&&(d.sx=q.width/2),d.sy===l&&(d.sy=q.height/2),d.sWidth=d.sWidth||q.width,d.sHeight=d.sHeight||q.height,
d.width&&!d.height?d.height=d.width/u:!d.width&&d.height?d.width=d.height*u:!d.width&&!d.height&&(d.width=q.width,d.height=q.height),z(a,d,d.width,d.height),a.drawImage(q,d.sx-d.sWidth/2,d.sy-d.sHeight/2,d.sWidth,d.sHeight,d.x-d.width/2,d.y-d.height/2,d.width,d.height),a.restore(),!0):!1}function b(){c(e);d.load&&d.load.call(h)}var e,h,d=f({},r,a),q=new D,u;q.src=d.source;for(a=0;a<this.length;a+=1)h=this[a],e=h.getContext("2d"),B(e,d),d.load?q.onload=b:c(e)||(q.onload=b);return this};d.drawPolygon=
function(a){var c,b=f({},r,a),e=v/b.sides,d=v/2+e,l=2*v/b.sides,q=F(l/2)*b.radius,u,k,n,t,g;b.closed=!0;if(2<b.sides)for(c=0;c<this.length;c+=1){a=this[c].getContext("2d");B(a,b);z(a,b,b.radius,b.radius);a.beginPath();for(g=0;g<b.sides;g+=1)u=b.x+b.radius*F(d),k=b.y+b.radius*K(d),n=b.x+(q+q*b.projection)*F(d+e),t=b.y+(q+q*b.projection)*K(d+e),0===g?a.moveTo(u,k):a.lineTo(u,k),b.projection&&a.lineTo(n,t),d+=l;a.restore();E(a,b)}return this};d.setPixels=function(a){var c,b,e,d=f({},r,a),p,q,u,k;for(b=
0;b<this.length;b+=1){c=this[b];a=c.getContext("2d");!d.x&&(!d.y&&!d.width&&!d.height)&&(d.width=c.width,d.height=c.height,d.x=d.width/2,d.y=d.height/2);z(a,d,d.width,d.height);p=a.getImageData(d.x-d.width/2,d.y-d.height/2,d.width,d.height);q=p.data;u=q.length;if(d.each!==l)for(e=0;e<u;e+=4)k=d.each.call(c,q[e],q[e+1],q[e+2],q[e+3]),q[e]=k[0],q[e+1]=k[1],q[e+2]=k[2],q[e+3]=k[3];a.putImageData(p,d.x-d.width/2,d.y-d.height/2);a.restore()}return this};x=[];d.drawLayers=function(a){var c,b,e;for(b=0;b<
this.length;b+=1){c=this[b].getContext("2d");a&&c.clearRect(0,0,this[b].width,this[b].height);for(e=0;e<x.length;e+=1)c=x[e],c.fn&&d[c.fn].call(this.eq(b),c)}return this};A.event.fix=function(a){a=y.call(A.event,a);a.layerX===l&&a.layerY===l&&(a.layerX=a.offsetX,a.layerY=a.offsetY);return a};w.defaults=C;w.prefs=r;w.setGlobals=B;w.convertAngles=L;w.rotate=z;w.layers=x;w.addLayer=I;w.retrofit=function(){w.retro=!0;w.queue=x;w.create=I;d.drawQueue=d.drawLayers;w.checkUnits=w.convertAngles;return w};
w.retro=!1;A.jCanvas=w})(jQuery,document,Math,Image);
