$(function(){function x(){$("#decodedlabel").hide();$("#decoded").hide();$("#allORFs").html("");var a=$("#sequence").attr("value"),a=E(a);H=a.length;var b=a;$("#length").html(b.length);for(var b=a,c=0,k=0;k<b.length;k++){var p=b.charAt(k);("g"==p||"G"==p||"c"==p||"C"==p)&&c++}k=0;0!=b.length&&(k=c/b.length);$("#perc").html(Math.round(100*k));$("#minlen").html(q);b=a;c=$("#scrollbar");c.find(".ui-slider-handle");k=$("#canvas").width();p=k/((1+b.length)*g);1<p&&(p=1);Math.round(p*c.width());c.slider("option",
"min",0);c.slider("option","max",Math.round(b.length-k/g));c.slider("option","value",b.length/4);m=b.length/4;F=A(a);D=A(B(a));C(a)}function E(a){return a.replace(/[^atgcu]/mig,"").replace(/t/mig,"u").toUpperCase()}function I(a){"G"==a?a="C":"g"==a?a="c":"C"==a?a="G":"c"==a?a="g":"a"==a?a="u":"A"==a?a="U":"T"==a?a="A":"t"==a?a="a":"u"==a?a="a":"U"==a&&(a="A");return a}function B(a){for(var b="",c=0;c<a.length;c++){var k=a.charAt(c);"G"==k?k="C":"g"==k?k="c":"C"==k?k="G":"c"==k?k="g":"a"==k?k="u":
"A"==k?k="U":"T"==k?k="A":"t"==k?k="a":"u"==k?k="a":"U"==k&&(k="A");b=k+b}return b}function l(){m=$("#scrollbar").slider("option","value");var a=$("#sequence").attr("value"),a=E(a);C(a)}function v(a,b,c,k){k.clearRect(0,0,b,c);k.fillStyle="#f0f0f0";k.fillRect(0,0,b,100)}function y(a,b,c,k,p){if(!(null==F||null==D)){b=p.fillStyle;p.fillStyle="#e0e0e0";p.fillRect(0,10,c,6);p.fillRect(0,18,c,6);p.fillRect(0,26,c,6);p.fillRect(0,35,c,12);p.fillRect(0,50,c,6);p.fillRect(0,58,c,6);p.fillRect(0,66,c,6);
k=a.length/c;for(var d=0,h=0,e=0,f=0;f<a.length;f++){var m=a.charAt(f);("g"==m||"G"==m||"c"==m||"C"==m)&&d++;h++;h>k&&(d=Math.round(256-256*d/h),p.fillStyle="rgb("+d+","+d+","+d+")",p.fillRect(e,35,1,12),d=h=0,e++)}for(f=0;3>f;f++)for(var d=F[f],m=h=0,g=f;g<a.length;g+=3)m+=3,e=d[g],"object"==typeof e&&h++,m>k&&(0<h&&(e=Math.round(g/a.length*c),p.fillStyle=h==m/3?"rgb(64,128,64)":"rgb(64,200,64)",p.fillRect(e,8*f+11,1,5)),m=h=0);for(f=0;3>f;f++){d=D[f];m=h=0;for(g=f;g<a.length;g+=3)m+=3,e=d[g],"object"==
typeof e&&h++,m>k&&(0<h&&h==m/3&&(e=Math.round(g/a.length*c),p.fillRect(c-e,8*(5+f)+11,1,5)),h=!1,m=0)}p.fillStyle=b}}function C(a){function b(a,c,k,J){"STOP"==a&&(a=(k-m)*g,c=135+15*c,h.beginPath(),h.moveTo(a,c),h.lineTo(a+3*g,c),h.lineTo(a+3*g+3*J,c+7),h.lineTo(a+3*g,c+r),h.lineTo(a,c+15),h.lineTo(a+3*J,c+7),h.fill(),h.closePath())}function c(a,b,k,J){"Met"==a&&(a=(k-m)*g,b=135+15*b,h.beginPath(),h.moveTo(a,b),h.lineTo(a+3*g,b),h.lineTo(a+3*g+3*J,b+7),h.lineTo(a+3*g,b+r),h.lineTo(a,b+15),h.lineTo(a+
3*J,b+7),h.fill(),h.closePath())}var k=document.getElementById("canvas"),p=k.width,u=k.height;p!=k.clientWidth&&(k.width=k.clientWidth,p=k.width,f=null);var h=k.getContext("2d");v(k,p,u,h);a!=d||e!=q||null==f?(y(a,k,p,u,h),f=h.getImageData(0,0,p,u),d=a,e=q):h.putImageData(f,0,0);u=10*Math.round(m/10);k=10*Math.round((m+p/g)/10);h.fillStyle="rgba(0,0,0,.5)";h.fillRect(u/a.length*p,5,(u-k)/a.length*p,70);h.fillStyle="#000000";h.beginPath();h.moveTo(0,100);h.lineTo(u/a.length*p,75);h.moveTo(k/a.length*
p,75);h.lineTo(p,100);h.stroke();h.closePath();h.font="bold 12px verdana";for(var n=u;n<=k;n+=10){var l=h.measureText(n).width;h.fillText(n,(n-m)*g-(l-g)/2,110);h.fillText(n,(n-m)*g-(l-g)/2,270);h.fillRect((n-m)*g,113,g,5);h.fillRect((n-m)*g,254,g,5)}h.font="normal 12px verdana";l=h.measureText("A").width;for(n=m;n<=Math.round(m+p/g);n++){var t=a.charAt(n);h.fillText(t,(n-m)*g-(l-g)/2,130);t=I(t);h.fillText(t,(n-m)*g-(l-g)/2,252)}h.lineWidth=0.25;h.beginPath();for(t=0;7>=t;t++)h.moveTo(0,135+15*t),
h.lineTo(p,135+15*t);for(n=u-3;n<=k;n+=1)t=n%3,h.moveTo((n-m)*g,135+t*r),h.lineTo((n-m)*g+3,142+t*r),h.lineTo((n-m)*g,150+t*r),h.moveTo((n-m)*g,195+t*r),h.lineTo((n-m)*g-3,202+t*r),h.lineTo((n-m)*g,210+t*r);h.stroke();h.closePath();oldFillStyle=h.fillStyle;h.fillStyle="#008000";for(n=3<u?u-3:0;n<=k;n+=1)t=n%3,"object"==typeof F[t][n]&&(l=(n-m)*g,p=15*t+139,h.fillRect(l,p,3*g,g/2)),"object"==typeof D[t][a.length-n]&&(l=(n-m)*g,p=15*(t+4)+139,h.fillRect(l,p,3*g,g/2));h.fillStyle="#ff0000";for(n=3<u?
u-3:0;n<=k;n+=1){var t=n%3,l=a.substring(n,n+3),p=CodonMap[l],s=CodonMap[B(l)];b(p,t,n,1);b(s,t+4,n,-1)}h.fillStyle=oldFillStyle;h.fillStyle="rgb(96,96,192)";for(n=3<u?u-3:0;n<=k;n+=1)t=n%3,l=a.substring(n,n+3),p=CodonMap[l],s=CodonMap[B(l)],c(p,t,n,1),c(s,t+4,n,-1);h.fillStyle=oldFillStyle;for(n=u-3;n<=k;n+=1)t=n%3,l=a.substring(n,n+3),p=CodonMap[l],s=CodonMap[B(l)],l=h.measureText(p).width,u=h.measureText(s).width,h.fillText(p,(n-m)*g+2-(l-3*g)/2,147+t*r),h.fillText(s,(n-m)*g-2-(u-3*g)/2,207+t*
r)}function K(){CodonMap={};for(aa in z)if("START"!=aa){var a=z[aa].codes;for(i in a)CodonMap[a[i]]=aa}}function w(b,c,d){if(100>=c){var k=document.getElementById("canvas").width,e=$("#sequence").attr("value"),e=E(e),k=Math.round((e.length-k/g)*b/k);0>k&&(k=0);k>e.length&&(k=e.length);e=$("#scrollbar");e.slider("option","value",k);l()}100<=c&&null!=d?(c=b-d.x,Math.abs(c)>g&&(k=Math.round(c/g),d.x+=k*g,e=$("#scrollbar"),m-=k,e.slider("option","value",m),l())):100<=c&&null==d&&(k=Math.round(b/g),k=
m+k-1,d=Math.ceil((c-135)/r),1<=d&&3>=d?(c=F[d-1][k],a={from:c.from,to:c.to,forward:!0},G(),console.info("decode forward on bpi: "+k+" row:"+d+" "+c.from+"-"+c.to)):5<=d&&7>=d&&(c=D[d-5][H-k],a={from:c.from,to:c.to,forward:!1},G(),console.info("decode reverse on bpi: "+k+" row:"+d+" "+c.from+"-"+c.to)))}function G(){$("#decodedlabel").show();$("#decoded").show();var b=a.from,d=a.to,e=a.forward,k=$("#sequence").attr("value"),k=E(k);e||(k=B(k));e="";for(b+=3;b<d;b+=3)var f=k.substring(b,b+3),f=CodonMap[f],
e=c?e+(f+" "):e+z[f].shortName;$("#decoded").html(e);$("#allORFs").html("")}function A(a,b){for(var c={},k=0;3>k;k++){c[k]={};for(var d=0,e=!1,h=k;h<a.length;h+=3){var f=a.substring(h,h+3),f=CodonMap[f];if("STOP"==f){if(h-d>=3*q)for(e={from:d,to:h};d<=h;d++)c[k][d]=e;d=h;e=!0}else!e&&"MET"==f&&(d=h,e=!0)}}return c}function s(a){for(var b=[],c=0;3>c;c++)for(var d=0,e=!1,f=c;f<a.length;f+=3){var h=a.substring(f,f+3),h=CodonMap[h];if("STOP"==h){if(f-d>=3*q){for(var e=f,m="",g="",f=d+3;f<e;f+=3)h=a.substring(f,
f+3),h=CodonMap[h],m+=z[h].shortName,g+=h+" ";b.push({from:d,to:f,l3:g,l1:m})}d=f;e=!0}else!e&&"MET"==h&&(d=f,e=!0)}return b}var z={Ala:{shortName:"A",codes:["GCU","GCC","GCA","GCG"],type:"Nonpolar",longName:"Alanine"},Leu:{shortName:"L",codes:"UUA UUG CUU CUC CUA CUG".split(" "),type:"Nonpolar",longName:"Leucine"},Arg:{shortName:"R",codes:"CGU CGC CGA CGG AGA AGG".split(" "),type:"Polar",longName:"Arginine"},Lys:{shortName:"K",codes:["AAA","AAG"],type:"Basic",longName:"Lysine"},Asn:{shortName:"N",
codes:["AAU","AAC"],type:"Polar",longName:"Asparagine"},Met:{shortName:"M",codes:["AUG"],type:"Nonpolar",longName:"Methionine"},Asp:{shortName:"D",codes:["GAU","GAC"],type:"Nonpolar",longName:"Aspartic acid"},Phe:{shortName:"F",codes:["UUU","UUC"],type:"Nonpolar",longName:"Phenylalanine"},Cys:{shortName:"C",codes:["UGU","UGC"],type:"Polar",longName:"Cysteine"},Pro:{shortName:"P",codes:["CCU","CCC","CCA","CCG"],type:"Nonpolar",longName:"Proline"},Gln:{shortName:"Q",codes:["CAA","CAG"],type:"Polar",
longName:"Glutamine"},Ser:{shortName:"S",codes:"UCU UCC UCA UCG AGU AGC".split(" "),type:"Polar",longName:"Serine"},Glu:{shortName:"E",codes:["GAA","GAG"],type:"Nonpolar",longName:"Glutamic acid"},Thr:{shortName:"T",codes:["ACU","ACC","ACA","ACG"],type:"Polar",longName:"Threonine"},Gly:{shortName:"G",codes:["GGU","GGC","GGA","GGG"],type:"Polar",longName:"Glycine"},Trp:{shortName:"W",codes:["UGG"],type:"Nonpolar",longName:"Tryptophan"},His:{shortName:"H",codes:["CAU","CAC"],type:"Basic",longName:"Histidine"},
Tyr:{shortName:"Y",codes:["UAU","UAC"],type:"Polar",longName:"Tyrosine"},Ile:{shortName:"I",codes:["AUU","AUC","AUA"],type:"Nonpolar",longName:"Isoleucine"},Val:{shortName:"V",codes:["GUU","GUC","GUA","GUG"],type:"Nonpolar",longName:"Valine"},START:{shortName:"START",codes:["AUG"],type:"START",longName:"Methionine"},STOP:{shortName:"STOP",codes:["UAG","UGA","UAA"],type:"STOP",longName:"Stop codon"}},q=80,m=0,g=12,r=15,F=null,D=null,H=-1,a=null,c=!0,b=null;(function(){var a=!0;Modernizr.canvas||(a=
!1);if(a){var b=navigator.userAgent.toLowerCase(),c;if(c=-1!=b.indexOf("mozilla")&&-1==b.indexOf("spoofer")&&-1==b.indexOf("compatible")&&-1==b.indexOf("opera")&&-1==b.indexOf("webtv")&&-1==b.indexOf("hotjava")){if("Gecko"!=navigator.product)c=-1;else{c=0;for(var d=navigator.userAgent.toLowerCase(),e=d.indexOf("rv:"),f=d.indexOf(")",e),d=d.substring(e+3,f).split("."),e=1,f=0;f<d.length;f++){var h=parseInt(d[f]);c+=h/e;e*=100}}c=2>c}if(c)a=!1;else{if(b=-1!=b.indexOf("msie")&&-1==b.indexOf("opera"))b=
-1,"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(b=parseFloat(RegExp.$1)),b=9>b;b&&(a=!1)}}a||alert("This site does support your browser. Please upgrade to modern browser.")})();(function(){K();$("#decodedlabel").hide();$("#decoded").hide();$("#sequence").change(function(){x()});$("#sequence").keypress(function(){x()});$("#new_window").button();$("#changelength").button();$("#changelength").click(function(){var a=Math.round(prompt("Minimum ORF length: ",
q));0<a&&1E4>a&&($("#wait").html("Recalculating putative ORFs"),$("#wait").dialog("open"),q=a,window.setTimeout(function(){$("#minlen").html(q);x();$("#wait").dialog("close")},10))});$("#decoded31").button();$("#decoded31").click(function(){(c=!this.checked)?$("#decoded31").button("option","label","3 letter code"):$("#decoded31").button("option","label","1 letter code");null!=a&&G()});$("#decodedblast").button();$("#decodedblast").click(function(){c=!1;$("#decoded31").button("option","label","1 letter code");
G();var a="http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&QUERY="+$("#decoded").html();window.open(a,"blast")});$("#reversecomplement").button();$("#reversecomplement").click(function(){$("#wait").html("Calculating reverse complement");$("#wait").dialog("open");window.setTimeout(function(){var a=E($("#sequence").attr("value")),a=B(a);$("#sequence").attr("value",a);x();$("#wait").dialog("close")},5)});$("#allorfs").button();$("#allorfs").click(function(){$("#wait").html("Calculating all ORFs, this may take a while...");
$("#wait").dialog("open");window.setTimeout(function(){$("#decodedlabel").hide();$("#decoded").hide();var a="",b=$("#sequence").attr("value"),b=E(b),d=s(b),b=s(B(b)),a=a+'<div style="background-color:rgb(225,255,225);font-weight:bold;font-size:18px;">Forward decoding</div><div style="width:100%;word-break:break-all">';for(i in d)var e=d[i],f="http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&QUERY="+e.l1,a=a+("<span style='width:600px'><b>Forward "+e.from+"-"+e.to+"</b></span> <a class='ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only' target='blast' style='height:20px;width:125px' href='"+
f+"'><span  style='font-size:12px;width:50px'> Run Blast search </span></a><br>"+(c?e.l3:e.l1)+"<br>");a+='</div><div style="background-color:rgb(225,255,225);font-weight:bold;font-size:18px;">Reverse decoding</div><div style="width:100%;word-break:break-all">';for(i in b)e=b[i],f="http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&QUERY="+e.l1,a+="<span style='width:600px'><b>Reverse "+e.from+"-"+e.to+"</b></span> <a class='ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only' target='blast' style='height:20px;width:125px' href='"+
f+"'><span  style='font-size:12px;width:50px'> Run Blast search </span></a><br>"+(c?e.l3:e.l1)+"<br>";$("#allORFs").html(a);$("#wait").dialog("close")},5)});$("#scrollbar").slider();$("#scrollbar").slider("option","slide",l);$("#canvas").click(function(a){var b=document.getElementById("canvas");w(a.pageX-b.offsetLeft,a.pageY-b.offsetTop,null)});$("#canvas").mousedown(function(a){var c=document.getElementById("canvas");b={x:a.pageX-c.offsetLeft,y:a.pageY-c.offsetTop};return!1});$("#canvas").mouseup(function(a){b=
null});$("#canvas").mousemove(function(a){if(null!=b){var c=document.getElementById("canvas");w(a.layerX-c.offsetLeft,a.layerY-c.offsetTop,b)}});Modernizr.touch&&$("#canvas").each(function(){this.ontouchstart=function(a){a=a.touches[0];var c=document.getElementById("canvas");b={x:a.clientX-c.offsetLeft,y:a.clientY-c.offsetTop}};this.ontouchmove=function(a){a=a.touches[0];var c=document.getElementById("canvas");w(a.clientX-c.offsetLeft,a.clientY-c.offsetTop,b)};this.ontouchend=function(a){b=null}});
$("#wait").dialog();$("#wait").html("Loading sample sequence");$("#wait").dialog("open");window.setTimeout(function(){$().ready(function(){$.ajax({url:"sequence.txt",success:function(a){$("#sequence").html(a);x()}});$("#wait").dialog("close")},10)})})();var d=null,e=0,f=null});(function(x,E,I,B,l){function v(a,c){a?c?(A=m({},A,a),s=m({},A)):s=m({},s,a):s=m({},A);return this}function y(a,c){a.fillStyle=c.fillStyle;a.strokeStyle=c.strokeStyle;a.lineWidth=c.strokeWidth;a.lineCap=c.strokeCap;a.lineJoin=c.strokeJoin;c.rounded&&(a.lineCap="round",a.lineJoin="round");a.shadowOffsetX=c.shadowX;a.shadowOffsetY=c.shadowY;a.shadowBlur=c.shadowBlur;a.shadowColor=c.shadowColor;a.globalAlpha=c.opacity;a.globalCompositeOperation=c.compositing}function C(a,c){c.mask&&(a.save(),a.clip());
c.closed?(a.closePath(),a.fill(),a.stroke()):(a.fill(),a.stroke(),a.closePath())}function K(a){return a.inDegrees?r/180:1}function w(a,c,b,d){var e=K(c);a.save();c.fromCenter||(c.x+=b/2,c.y+=d/2);c.angle&&(a.translate(c.x,c.y),a.rotate(c.angle*e),a.translate(-c.x,-c.y));return e}function G(a){z.push(a);return a}var A,s,z,q=x.fn,m=x.extend,g=x.event.fix,r=I.PI,F=I.round,D=I.sin,H=I.cos;A={width:0,height:0,cornerRadius:0,fillStyle:"transparent",strokeStyle:"transparent",strokeWidth:1,strokeCap:"butt",
strokeJoin:"miter",rounded:!1,shadowX:0,shadowY:0,shadowBlur:3,shadowColor:"transparent",opacity:1,compositing:"source-over",mask:!1,x:0,y:0,x1:0,y1:0,x2:0,y2:0,radius:0,start:0,end:360,ccw:!1,inDegrees:!0,fromCenter:!0,closed:!1,sides:3,angle:0,text:"",font:"normal 12pt sans-serif",align:"center",baseline:"middle",source:"",repeat:"repeat"};s=m({},A);q.jCanvas=v;q.loadCanvas=function(a){return this[0].getContext(a||"2d")};q.draw=function(a){var c;for(c=0;c<this.length;c+=1)a.call(this[c],this[c].getContext("2d"));
return this};q.gradient=function(a){var c=this[0].getContext("2d");a=m({},s,a);for(var b,d=0,e=1,c=a.r1!==l||a.r2!==l?c.createRadialGradient(a.x1,a.y1,a.r1,a.x2,a.y2,a.r2):c.createLinearGradient(a.x1,a.y1,a.x2,a.y2);a["c"+e]!==l;)d+=1,e+=1;for(e=1;e<=d;e+=1)b=F(100/(d-1)*(e-1))/100,a["s"+e]===l&&(a["s"+e]=b),c.addColorStop(a["s"+e],a["c"+e]);return c};q.pattern=function(a){function c(){return f.complete?(g=d.createPattern(f,e.repeat),!0):!1}function b(){c();e.load&&e.load.call(this[0],g)}var d=this[0].getContext("2d"),
e=m({},s,a),f=new B,g;f.src=e.source;e.load?f.onload=b:c()||(f.onload=b);return g};q.clearCanvas=function(a){var c,b,d=m({},s,a);for(b=0;b<this.length;b+=1)c=this[b].getContext("2d"),w(c,d,d.width,d.height),a?c.clearRect(d.x-d.width/2,d.y-d.height/2,d.width,d.height):c.clearRect(0,0,this[b].width,this[b].height);return this};q.saveCanvas=function(){for(var a=0;a<this.length;a+=1)this[a].getContext("2d").save();return this};q.restoreCanvas=function(){for(var a=0;a<this.length;a+=1)this[a].getContext("2d").restore();
return this};q.scaleCanvas=function(a){var c,b=m({},s,a);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),a.save(),a.translate(b.x,b.y),a.scale(b.width,b.height),a.translate(-b.x,-b.y);return this};q.translateCanvas=function(a){var c,b=m({},s,a);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),a.save(),a.translate(b.x,b.y);return this};q.rotateCanvas=function(a){var c,b=m({},s,a);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),w(a,b,0,0);return this};q.drawRect=function(a){var c,b=
m({},s,a),d,e,f,g,l;for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),y(a,b),w(a,b,b.width,b.height),b.cornerRadius?(d=b.x-b.width/2,e=b.y-b.height/2,f=b.x+b.width/2,g=b.y+b.height/2,l=b.cornerRadius,0>f-d-2*l&&(l=(f-d)/2),0>g-e-2*l&&(l=(g-e)/2),a.beginPath(),a.moveTo(d+l,e),a.lineTo(f-l,e),a.arc(f-l,e+l,l,3*r/2,2*r),a.lineTo(f,g-l),a.arc(f-l,g-l,l,0,r/2),a.lineTo(d+l,g),a.arc(d+l,g-l,l,r/2,r),a.lineTo(d,e+l),a.arc(d+l,e+l,l,r,3*r/2)):(a.beginPath(),a.rect(b.x-b.width/2,b.y-b.height/2,b.width,
b.height),a.restore()),C(a,b);return this};q.drawArc=function(a){var c,b,d=m({},s,a);!d.inDegrees&&360===d.end&&(d.end=2*r);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),y(a,d),b=w(a,d,d.radius,d.radius),a.beginPath(),a.arc(d.x,d.y,d.radius,d.start*b-r/2,d.end*b-r/2,d.ccw),a.restore(),C(a,d);return this};q.drawEllipse=function(a){var c,b=m({},s,a),d=b.width*(4/3);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),y(a,b),w(a,b,b.width,b.height),a.beginPath(),a.moveTo(b.x,b.y-b.height/2),
a.bezierCurveTo(b.x-d/2,b.y-b.height/2,b.x-d/2,b.y+b.height/2,b.x,b.y+b.height/2),a.bezierCurveTo(b.x+d/2,b.y+b.height/2,b.x+d/2,b.y-b.height/2,b.x,b.y-b.height/2),a.restore(),C(a,b);return this};q.drawLine=function(a){var c,b=m({},s,a),d=2,e,f;for(c=0;c<this.length;c+=1){a=this[c].getContext("2d");y(a,b);a.beginPath();for(a.moveTo(b.x1,b.y1);;){e=b["x"+d];f=b["y"+d];if(e!==l&&f!==l)a.lineTo(e,f);else break;d+=1}C(a,b)}return this};q.drawQuad=function(a){var c,b=m({},s,a),d=2,e,f,g,q;for(c=0;c<this.length;c+=
1){a=this[c].getContext("2d");y(a,b);a.beginPath();for(a.moveTo(b.x1,b.y1);;){e=b["x"+d];f=b["y"+d];g=b["cx"+(d-1)];q=b["cy"+(d-1)];if(e!==l&&f!==l&&g!==l&&q!==l)a.quadraticCurveTo(g,q,e,f);else break;d+=1}C(a,b)}return this};q.drawBezier=function(a){var c,b=m({},s,a),d=2,e=1,f,g,q,r,k,p;for(c=0;c<this.length;c+=1){a=this[c].getContext("2d");y(a,b);a.beginPath();for(a.moveTo(b.x1,b.y1);;){f=b["x"+d];g=b["y"+d];q=b["cx"+e];r=b["cy"+e];k=b["cx"+(e+1)];p=b["cy"+(e+1)];if(f!==l&&g!==l&&q!==l&&r!==l&&
k!==l&&p!==l)a.bezierCurveTo(q,r,k,p,f,g);else break;d+=1;e+=2}C(a,b)}return this};q.drawText=function(a){var c,b=m({},s,a);for(c=0;c<this.length;c+=1)a=this[c].getContext("2d"),y(a,b),a.textBaseline=b.baseline,a.textAlign=b.align,a.font=b.font,a.strokeText(b.text,b.x,b.y),a.fillText(b.text,b.x,b.y);return this};q.drawImage=function(a){function c(a){return g.complete?(q=g.width/g.height,f.sx===l&&(f.sx=g.width/2),f.sy===l&&(f.sy=g.height/2),f.sWidth=f.sWidth||g.width,f.sHeight=f.sHeight||g.height,
f.width&&!f.height?f.height=f.width/q:!f.width&&f.height?f.width=f.height*q:!f.width&&!f.height&&(f.width=g.width,f.height=g.height),w(a,f,f.width,f.height),a.drawImage(g,f.sx-f.sWidth/2,f.sy-f.sHeight/2,f.sWidth,f.sHeight,f.x-f.width/2,f.y-f.height/2,f.width,f.height),a.restore(),!0):!1}function b(){c(d);f.load&&f.load.call(e)}var d,e,f=m({},s,a),g=new B,q;g.src=f.source;for(a=0;a<this.length;a+=1)e=this[a],d=e.getContext("2d"),y(d,f),f.load?g.onload=b:c(d)||(g.onload=b);return this};q.drawPolygon=
function(a){var c,b=m({},s,a),d=r/b.sides,e=r/2+d,f=2*r/b.sides,g=H(f/2)*b.radius,l,q,k,p,u;b.closed=!0;if(2<b.sides)for(c=0;c<this.length;c+=1){a=this[c].getContext("2d");y(a,b);w(a,b,b.radius,b.radius);a.beginPath();for(u=0;u<b.sides;u+=1)l=b.x+b.radius*H(e),q=b.y+b.radius*D(e),k=b.x+(g+g*b.projection)*H(e+d),p=b.y+(g+g*b.projection)*D(e+d),0===u?a.moveTo(l,q):a.lineTo(l,q),b.projection&&a.lineTo(k,p),e+=f;a.restore();C(a,b)}return this};q.setPixels=function(a){var c,b,d,e=m({},s,a),f,g,q,r;for(b=
0;b<this.length;b+=1){c=this[b];a=c.getContext("2d");!e.x&&(!e.y&&!e.width&&!e.height)&&(e.width=c.width,e.height=c.height,e.x=e.width/2,e.y=e.height/2);w(a,e,e.width,e.height);f=a.getImageData(e.x-e.width/2,e.y-e.height/2,e.width,e.height);g=f.data;q=g.length;if(e.each!==l)for(d=0;d<q;d+=4)r=e.each.call(c,g[d],g[d+1],g[d+2],g[d+3]),g[d]=r[0],g[d+1]=r[1],g[d+2]=r[2],g[d+3]=r[3];a.putImageData(f,e.x-e.width/2,e.y-e.height/2);a.restore()}return this};z=[];q.drawLayers=function(a){var c,b,d;for(b=0;b<
this.length;b+=1){c=this[b].getContext("2d");a&&c.clearRect(0,0,this[b].width,this[b].height);for(d=0;d<z.length;d+=1)c=z[d],c.fn&&q[c.fn].call(this.eq(b),c)}return this};x.event.fix=function(a){a=g.call(x.event,a);a.layerX===l&&a.layerY===l&&(a.layerX=a.offsetX,a.layerY=a.offsetY);return a};v.defaults=A;v.prefs=s;v.setGlobals=y;v.convertAngles=K;v.rotate=w;v.layers=z;v.addLayer=G;v.retrofit=function(){v.retro=!0;v.queue=z;v.create=G;q.drawQueue=q.drawLayers;v.checkUnits=v.convertAngles;return v};
v.retro=!1;x.jCanvas=v})(jQuery,document,Math,Image);
